# -*- coding: utf-8 -*-
"""Tensorflow_Keras_installing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6PBYaZ3YbxgGjMoIPqhv-_wlPT8k4n-
"""

pip install tensorflow

pip install keras mnist